### ISSUE TITLE
Fix zero value of main_precursor_charge field

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#10]
mzDB files generated from Wiff files contain a charge of zero for all MS2 spectra

**Comment by jerkos** [comment]
Yes, I have already seen that. Seems that charge info is not present in Wiff files or Proteowizard does not give any acces to it yet !

**Comment by david-bouyssie** [comment]
Ok we will try the conversion with msconvert to see if the exported MGF file has a valid charge state.

**Comment by david-bouyssie** [comment]
Without specific peak picking procedure, the charge state is not computed by msconvert.
We made also a conversion with MSDataConverter (AbSciex tool) and the result is the same (no charge state computed).
I will fix mzdb-access so that it does not write zero charge states in the exported MGF file.
