### ISSUE TITLE
The isolation window is not exported from AbSciex files

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#11]
mzDB files created from wiff files do not contain the isolationWindow XML tag in the precursor_list field.
Is this information available from the AbSciex  API ?

**Comment by jerkos** [comment]
After reading the source code of ABI WiffFIile.cpp

<pre>
<code>
 virtual bool getHasIsolationInfo() const;
 virtual void getIsolationInfo(double& centerMz, double& lowerLimit, double& upperLimit) const;
</code>
</pre>

But they are never called in SpectrumList_ABI.cpp.

**Comment by david-bouyssie** [comment]
Ok it would be great if they were included in the mzDB files. Is it possible ?

**Comment by jerkos** [comment]
I tested on a file I have, getHasIsolationInfo always return false !

**Comment by david-bouyssie** [comment]
Is it a DDA or a DIA file ?

**Comment by jerkos** [comment]
it is a DDA file

**Comment by jerkos** [comment]
fix by commit 04db4f3d73944bf2c3d3b3ff851f639d4e8832ad
