### ISSUE TITLE
Fitted data contain zero values in left and right HWHMs (name updated)

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#15]
MS2 Data read from mzdb-access contain always zero values for the fitted peaks.
It seems that left and right HWHMs are not computed/persisted in the mzDB files.

Note that the problem may be identical for MS1 data.

**Comment by jerkos** [comment]
For now, they are simply not computed. We got direct access to centroids (directly provided by ABSciex) which are simply better than those we could have computed. 

We have 2 solutions here:
- compute ourselves centroids at the risk they are not good enough.
- get centroids from ABSciex and go back to the profile spectrum to estimate HWHMs, wihch is far more complicated.

So for the moment, I prefered keeping the best centroids. But, it's clear we have to think about FITTED mode.

**Comment by david-bouyssie** [comment]
I think we should try to the both methods. msconvert has a "prefer vendor peak picking" filter we could implement in the command line arguments.
The format is:
peakPicking <prefer_vendor> <ms_levels>
Example: peakPicking true [2,3] => use vendor centroiding for msLevels in [2,3]
Example: peakPicking false [1,2] => use PWIZ centroiding for msLevels in [1,2]

I agree that ABSciex centroids are a good starting point. You could try to detect minima values between consecutive centroids, and then submit the data points belonging to a given peak (or a peak group) to ceres (maybe centroids can be provided as parameters ?). It won't be an optimal solution, but I have the feeling that for MS2 data it may provide reasonable results.

What about MS1 data ?

**Comment by AlexandreBurel** [comment]
Fitted data are computed since version 0.9.9
It's available on Thermo, Bruker and AB Sciex data, do not hesitate to create issues if you find that data is miscalculated or could be improved :)
