### ISSUE TITLE
Fix mzdb param_tree for DIA dataset

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#16]
The bounding boxes sizes described in the param_tree of the mzdb are incorrect.
They do not correspond to those used to split the data.

**Comment by jerkos** [comment]
When the _--dia_ argument is passed, _bbHeightMSn_ and _bbWidthMSn_ if they are also passed will be **ignored** and set to **ms1 equivalents** (fix in  9d96ccf) . 

Supporting this would have complexify _a lot_ the dia/swath class for minor advantages.

**Comment by david-bouyssie** [comment]
Could you warn a message in the console about ignored parameters ?
Could you display the different used sizes ?

**Comment by jerkos** [comment]
:+1:  yep
