### ISSUE TITLE
Error in bb_first_spectrum_id (DIA datasets)

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#17]
The value spectrum.bb_first_spectrum_id seems to be incorrect for mzDB files generated from thermo DIA datasets (with the command line arguments --dia -t 15 -m 5).
When the corresponding bounding box is read it doesn't contain the corresponding spectrum.
However using the id of the specturm to query on bounding_box.first_spectrum_id loads a BB containing the desired spectrum.

Performing the query "SELECT DISTINCT first_spectrum_id FROM bounding_box" returns a consecutive list of IDs as if each spectrum was represented by a BB.

**Comment by jerkos** [comment]
found a little bug in the DIA consumer concerning spectrum.bb_first_spectrum_id(fix in  9d96ccf). But, I do not know if it fixes your problem since I did not set up mzDBAccess to extract some data. I am going to upload a new binary release in a minute.

**Comment by jerkos** [comment]
Can I close this one ?

**Comment by david-bouyssie** [comment]
I still have the same issue.
Trying to load a given spectrum by its id is not working.
The reason is that the bb_first_spectrum_id is still not the good one.
For instance in a file I'm searching for the spectrum 11327.
The bb_first_spectrum_id is 11318.
The bouding boxes having the first_spectrum_id equaling 11318 do not contain the spectrum 11327.
However some bounding boxes have a first_spectrum_id equaling 11327. These ones contain the desired spectrum.
What might help you is that 11318 is a spectrum corresponding to the first DIA window while 11327 is in the 10th DIA window.
It seems that first_bb_spectrum_id are always mapped with the first DIA LC-MS/MS map instead of the correct one.

**Comment by david-bouyssie** [comment]
Works for me now with the latest binaries !
