### ISSUE TITLE
bounding_box_msn_rtree is created for DDA acquisition

### ISSUE THREAD

**Issue by jturbet** [mzdb/pwiz-mzdb#18]
in version 0.9.8 of mzdb DDA files, bounding_box_msn_rtree is not empty as it should be. min_parent_mz and max_parent_mz contains value '0.0'

**Comment by jerkos** [comment]
I think this a normal behavior ? May @david-bouyssie  could comment on this ?

**Comment by david-bouyssie** [comment]
I was not certain that 'bounding_box_msn_rtree' was a full replacement of 'bounding_box_rtree'.
We have to choose if 'bounding_box_msn_rtree' could be used for both DDA/DIA experiments or if we use 'bounding_box_rtree' for DDA and 'bounding_box_msn_rtree' for DIA...

**Comment by jerkos** [comment]
I think we decided to use _bounding_box_msn_rtree_ index for both DDA and DIA. It is simpler i think !

**Comment by david-bouyssie** [comment]
Ok. In practice the 'bounding_box_rtree' is still used by mzdb-access.
We have to check if in the version 0.9.8 everything is fine with 'bounding_box_msn_rtree', so that we can remove the old 'bounding_box_rtree'. We have also to check if there is any the performance difference.
