### ISSUE TITLE
invalid data_encoding for MS1 spectra of DDA files

### ISSUE THREAD

**Issue by jturbet** [mzdb/pwiz-mzdb#19]
in 0.9.8 files generated without parameters:
3 data_encoding are created

<pre>
1   fitted  none    little_endian   64  32
2   centroid    none    little_endian   64  32
3   centroid    none    little_endian   32  32
</pre>

MS1 spectra are linked to the second data_encoding but should be linked to the first one.
<pre>update spectrum set data_encoding_id=1 where data_encoding_id=2</pre> fixes this issue

**Comment by jerkos** [comment]
fix with commit 44a0e6d2effae9ee8ba7beacb89c7ab72b177497
