### ISSUE TITLE
First compilation issue

### ISSUE THREAD

**Issue by jturbet** [mzdb/pwiz-mzdb#20]
I tried to compile pwiz-mzdb from scratch, following instructions: source checkout from github, unzip lib and compile with given arguments (command line).
After a long successful compilation time, 5 errors occured avoiding raw2mzdb executable generation. I checked/changed few configuration points without success

Config: Windows 7 enterprise, Visual Studio 2010 (that were already installed)
I tries: the github trunk and the 0.9.8 tag (same result)

  If someone has any clue it wouls be helpful

  JeT

extracted errors:

<pre>
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\getopt_pp\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\getopt_pp.dll
msvc.manifest.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\getopt_pp\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\getopt_pp.dll
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.dll
boost_filesystem-vc100-mt.lib(boost_filesystem-vc100-mt.dll) : error LNK2005: "public: __cdecl boost::filesystem::path::~path(void)" (??1path@filesystem@boost@@QEAA@XZ) déjà défini(e) dans libSHA1.lib(SHA1.obj)
   Création de la bibliothèque D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.lib et de l'objet D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.exp
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.dll : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés

        call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
link /NOLOGO /INCREMENTAL:NO /DLL /MACHINE:X64 /subsystem:console /out:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.dll" /IMPLIB:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.lib"   /OPT:REF,ICF @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\misc\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_misc.dll.rsp" 
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.dll
   Création de la bibliothèque D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.lib et de l'objet D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.exp
Chemistry.obj : error LNK2019: symbole externe non résolu "class boost::nowide::details::winconsole_ostream boost::nowide::cout" (?cout@nowide@boost@@3Vwinconsole_ostream@details@12@A) référencé dans la fonction "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl pwiz::chemistry::Element::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct pwiz::chemistry::Element::Info::Record const &)" (??6Element@chemistry@pwiz@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV34@AEBURecord@Info@012@@Z)
IsotopeTable.obj : error LNK2001: symbole externe non résolu "class boost::nowide::details::winconsole_ostream boost::nowide::cout" (?cout@nowide@boost@@3Vwinconsole_ostream@details@12@A)
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.dll : fatal error LNK1120: 1 externes non résolus

        call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
link /NOLOGO /INCREMENTAL:NO /DLL /MACHINE:X64 /subsystem:console /out:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.dll" /IMPLIB:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.lib"   /OPT:REF,ICF @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\chemistry\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_chemistry.dll.rsp" 
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\kyoto_cabinet\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\kyoto_cabinet.dll
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.dll
   Création de la bibliothèque D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.lib et de l'objet D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.exp
erf.obj : error LNK2019: symbole externe non résolu "class boost::nowide::details::winconsole_ostream boost::nowide::cout" (?cout@nowide@boost@@3Vwinconsole_ostream@details@12@A) référencé dans la fonction "class std::complex<double> __cdecl pwiz::math::erf_series2(class std::complex<double> const &)" (?erf_series2@math@pwiz@@YA?AV?$complex@N@std@@AEBV34@@Z)
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.dll : fatal error LNK1120: 1 externes non résolus

        call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
link /NOLOGO /INCREMENTAL:NO /DLL /MACHINE:X64 /subsystem:console /out:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.dll" /IMPLIB:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.lib"   /OPT:REF,ICF @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\utility\math\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pwiz_utility_math.dll.rsp" 
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
msvc.manifest.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\kyoto_cabinet\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\kyoto_cabinet.dll
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\pugixml\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pugixml.dll
msvc.manifest.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\pugixml\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\pugixml.dll
msvc.link.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\sqlite3\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\sqlite3.dll
msvc.manifest.dll D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\lib\sqlite3\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\sqlite3.dll
msvc.link D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\iterationBench.exe
LINK : warning LNK4044: option '/HIGHENTROPYVA:NO' non reconnue ; ignorée
iterationBench.obj : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ) référencé dans la fonction main$catch$0
libmzdb_utils.lib(mzDBFile.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ)
iterationBench.obj : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) référencé dans la fonction main$catch$0
libmzdb_utils.lib(mzDBFile.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
iterationBench.obj : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z) référencé dans la fonction main$catch$0
libmzdb_utils.lib(mzDBFile.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z)
libmzdb_utils.lib(mzDBFile.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z) référencé dans la fonction "public: bool __cdecl mzdb::MzDBFile::isNoLoss(void)" (?isNoLoss@MzDBFile@mzdb@@QEAA_NXZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z)
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\iterationBench.exe : fatal error LNK1120: 4 externes non résolus

        call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
link /NOLOGO /INCREMENTAL:NO /MACHINE:X64 /subsystem:console /out:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\iterationBench.exe" /LIBPATH:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz_aux\msrc\utility\vendor_api\Bruker\x64" /HIGHENTROPYVA:NO /OPT:REF,ICF @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\iterationBench.exe.rsp"  /MANIFESTDEPENDENCY:"type='win32' name='Interop.EDAL.SxS' version='1.0.0.0'"  /MANIFESTDEPENDENCY:"type='win32' name='Interop.HSREADWRITELib.SxS' version='1.0.0.0'"  /MANIFESTDEPENDENCY:"type='win32' name='MSFileReader.XRawfile2.SxS' version='3.0.29.0'"
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
...failed msvc.link D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\iterationBench.exe...
msvc.link D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\regionExtractorBench.exe
LINK : warning LNK4044: option '/HIGHENTROPYVA:NO' non reconnue ; ignorée
libmzdb_utils.lib(mzDBFile.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z) référencé dans la fonction "public: bool __cdecl mzdb::MzDBFile::isNoLoss(void)" (?isNoLoss@MzDBFile@mzdb@@QEAA_NXZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z)
libmzdb_utils.lib(mzDBFile.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ) référencé dans la fonction "public: bool __cdecl mzdb::MzDBFile::isNoLoss(void)" (?isNoLoss@MzDBFile@mzdb@@QEAA_NXZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ)
libmzdb_utils.lib(mzDBFile.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) référencé dans la fonction "public: bool __cdecl mzdb::MzDBFile::isNoLoss(void)" (?isNoLoss@MzDBFile@mzdb@@QEAA_NXZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
libmzdb_utils.lib(mzDBFile.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z) référencé dans la fonction "public: bool __cdecl mzdb::MzDBFile::isNoLoss(void)" (?isNoLoss@MzDBFile@mzdb@@QEAA_NXZ)
libmzdb_reader.lib(mzDBReader.obj) : error LNK2001: symbole externe non résolu "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z)
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\regionExtractorBench.exe : fatal error LNK1120: 4 externes non résolus

        call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
link /NOLOGO /INCREMENTAL:NO /MACHINE:X64 /subsystem:console /out:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\regionExtractorBench.exe" /LIBPATH:"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz_aux\msrc\utility\vendor_api\Bruker\x64" /HIGHENTROPYVA:NO /OPT:REF,ICF @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\regionExtractorBench.exe.rsp"  /MANIFESTDEPENDENCY:"type='win32' name='Interop.EDAL.SxS' version='1.0.0.0'"  /MANIFESTDEPENDENCY:"type='win32' name='Interop.HSREADWRITELib.SxS' version='1.0.0.0'"  /MANIFESTDEPENDENCY:"type='win32' name='MSFileReader.XRawfile2.SxS' version='3.0.29.0'"
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
    
...failed msvc.link D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\regionExtractorBench.exe...
compile-c-c++ D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\data\vendor_readers\Bruker\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\Reader_Bruker_Detail.obj
Reader_Bruker_Detail.cpp
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz\data\vendor_readers\Bruker\Reader_Bruker_Detail.cpp(41) : warning C4273: 'pwiz::msdata::detail::Bruker::format'ÿ: liaison DLL incoh‚rente
        .\pwiz/data/vendor_readers/Bruker/Reader_Bruker_Detail.hpp(63)ÿ: voir la d‚finition pr‚c‚dente de 'format'
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz\data\vendor_readers\Bruker\Reader_Bruker_Detail.cpp(124) : warning C4273: 'pwiz::msdata::detail::Bruker::createInstrumentConfigurations'ÿ: liaison DLL incoh‚rente
        .\pwiz/data/vendor_readers/Bruker/Reader_Bruker_Detail.hpp(66)ÿ: voir la d‚finition pr‚c‚dente de 'createInstrumentConfigurations'
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz\data\vendor_readers\Bruker\Reader_Bruker_Detail.cpp(263) : error C2491: 'pwiz::msdata::detail::Bruker::translateAsInstrumentSeries'ÿ: d‚finition de fonction dllimport non autoris‚e
D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\pwiz\data\vendor_readers\Bruker\Reader_Bruker_Detail.cpp(282) : error C2491: 'pwiz::msdata::detail::Bruker::translateAsAcquisitionSoftware'ÿ: d‚finition de fonction dllimport non autoris‚e

    call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
cl /Zm800 -nologo @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz\data\vendor_readers\Bruker\msvc-10.0\release\address-model-64\asynch-exceptions-on\threading-multi\Reader_Bruker_Detail.obj.rsp" 

.\pwiz/data/vendor_readers/ABI/SpectrumList_ABI.hpp(43) : error C2011: 'pwiz::msdata::detail::SpectrumList_ABI'ÿ: red‚finition du type 'class'
        .\pwiz/data/vendor_readers/ABI/SpectrumList_ABI.hpp(43)ÿ: voir la d‚claration de 'pwiz::msdata::detail::SpectrumList_ABI'
.\pwiz/data/vendor_readers/ABI/T2D/SpectrumList_ABI_T2D.hpp(38) : error C2011: 'pwiz::msdata::detail::SpectrumList_ABI_T2D'ÿ: red‚finition du type 'class'
        .\pwiz/data/vendor_readers/ABI/T2D/SpectrumList_ABI_T2D.hpp(38)ÿ: voir la d‚claration de 'pwiz::msdata::detail::SpectrumList_ABI_T2D'
pwiz_mzdb\mzdb\writer\mzdb_writer.cpp(76) : error C2680: 'pwiz::msdata::detail::SpectrumList_ABI *'ÿ: type de cible non valide pour dynamic_cast
        'pwiz::msdata::detail::SpectrumList_ABI'ÿ: la classe doit ˆtre d‚finie avant une utilisation dans un dynamic_cast
pwiz_mzdb\mzdb\writer\mzdb_writer.cpp(86) : error C2680: 'pwiz::msdata::detail::SpectrumList_ABI_T2D *'ÿ: type de cible non valide pour dynamic_cast
        'pwiz::msdata::detail::SpectrumList_ABI_T2D'ÿ: la classe doit ˆtre d‚finie avant une utilisation dans un dynamic_cast

    call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
cl /Zm800 -nologo @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\writer\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\mzdb_writer.obj.rsp" 

...failed compile-c-c++ D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\mzdb\writer\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\mzdb_writer.obj...
.\pwiz/data/vendor_readers/ABI/SpectrumList_ABI.hpp(43) : error C2011: 'pwiz::msdata::detail::SpectrumList_ABI'ÿ: red‚finition du type 'class'
        .\pwiz/data/vendor_readers/ABI/SpectrumList_ABI.hpp(43)ÿ: voir la d‚claration de 'pwiz::msdata::detail::SpectrumList_ABI'
.\pwiz/data/vendor_readers/ABI/T2D/SpectrumList_ABI_T2D.hpp(38) : error C2011: 'pwiz::msdata::detail::SpectrumList_ABI_T2D'ÿ: red‚finition du type 'class'
        .\pwiz/data/vendor_readers/ABI/T2D/SpectrumList_ABI_T2D.hpp(38)ÿ: voir la d‚claration de 'pwiz::msdata::detail::SpectrumList_ABI_T2D'

    call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\vc\vcvarsall.bat" amd64 >nul
cl /Zm800 -nologo @"D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\raw2mzDB.obj.rsp" 

...failed compile-c-c++ D:\Dev\projects_JeT\c++\pwiz-mzdb\dev\pwiz-mzdb\build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi\raw2mzDB.obj...

</pre>

**Comment by jerkos** [comment]
Hi
Just commited something that could help. 
You should follow the same procedure as you did, hope it will works.

**Comment by AlexandreBurel** [comment]
Fixed by Jerkos
