### ISSUE TITLE
Sample name issues (empty field or record)

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#24]
The sample name is always empty for AbSciex wiff files (a record is created but with an empty sample name field). Observed on version 0.9.8.

For Thermo raw files, the sample name information is not always retrieved (no sample record in the table) for raw files coming from the same acquisition sequence. ~~This bug has been observed for raw files converted using the version 0.9.7.~~ After verification it seems that this second problem has been observed for thermo raw files converted with an old version of PWIZ-mzDB (version 0.8). It seems to work since version 0.9.5.

**Comment by AlexandreBurel** [comment]
Sample name is now returned when available
It is still not functional on Bruker data, maybe it would require an update of ProteoWizard...
