### ISSUE TITLE
Bad accession number for "acquisition parameter"

### ISSUE THREAD

**Issue by david-bouyssie** [mzdb/pwiz-mzdb#26]
Here is the content of the param_tree column in the run table.

```
<params>
<cvParams>
<cvParam cvRef="MS" accession="1001954" name="acquisition parameter" value="SWATH acquisition" />
</cvParams>
</params>
```

The accession value should be "MS:1001954" instead of "1001954".

**Comment by IbrahimYapici** [comment]
Should accession be MS:1001954 if and only if cvRef is "MS" ? Are there any other cvRef values or any other case ?

**Comment by david-bouyssie** [comment]
Yes the accession prefix must equal the CvRef.
As an example see here: http://www.peptideatlas.org/tmp/mzML1.1.0.html#cvParam

Other CvRef values maybe UNIMOD but not in the context of mzDB:

```
<cvParam accession="UNIMOD:35" name="Oxidation" cvRef="UNIMOD"/>
```

**Comment by IbrahimYapici** [comment]
This issue is fixed for params_tree column of run table. There are 8 other occurences in mzdb_writer.cpp and 1 more in spectrum_inserter.h. 
Actual fix code is wrote in mzdb_writer.cpp and applied to this previous case. 
So : 
- Should it be applied to other case ? ( cf. ISerializer::serialize in files)
- Where is the best place to include the fixing code ?

**Comment by jerkos** [comment]
Yep, I think it must be applied to all others occurences. And the best way, I think is to modify the ISerializer::serialize mixin. I read the code and I think you can easily concatenate CvRef and the accession number (there is a small comment on that).

**Comment by IbrahimYapici** [comment]
That's what I thought to do if applied to all occurences : add in ISerilizer:serialize code. I'm going to do that.

**Comment by AlexandreBurel** [comment]
This issue has been solved already
If similar problems occur again, I'll create new issues
