### ISSUE TITLE
Unable to find file while building

### ISSUE THREAD

**Issue by LaChoz** [mzdb/pwiz-mzdb#29]
Hi,

I've installed MSVC 10 together with bjam and followed the protocole given on the main page project.

When building, i have : 
error: Unable to find file or target named
error: /c:/pwiz-mzdb-master/pwiz_mzdb/mzdb/writer//../lib/gsl.lib

i know this file is in project_root/pwiz_mzdb/mzdb/lib as stated in the description, i've tried copying them in diverse folders but the build process never finds it, and because i have a "//../" in the error description I don't know the precise path the build process is looking for.

Thank you for telling me the exact path where to place those files.

Adrien.

**Comment by AlexandreBurel** [comment]
Hi,

Have you tried this ?

> Unzip pwiz-mzdb-lib.zip file (containing project dependencies as static compiled libraries) located in project_root/pwiz_mzdb/mzdb/lib directory

For your information, having a double slash in your path has no consequences, it's just the same as a single slash. So your "true" path is /c:/pwiz-mzdb-master/pwiz_mzdb/mzdb/lib/gsl.lib

**Comment by LaChoz** [comment]
yes i already unzipped this zip file.

What I meant with //../ is that I was under the impression the path was too long to be displayed in the terminal.
I edited the jamfile.jam in C:\pwiz-mzdb-master\pwiz_mzdb\mzdb\writer and manualy wrote the correct path to find each files.

Now I have this :

`C:\pwiz-mzdb-master>quickbuild -j8 address-model=64 pwiz_mzdb --i-agree-to-the-v
endor-licenses
Build started at 12:05:18.07
Building pwiz (64-bit)...
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\a
bi\LicenseKey.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\baf2sql_c.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\baf2sql_cpp.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\schema.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\cdtdefs.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\compresseddatacluster.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawChromatogramReader.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawDataFile.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawDefs.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawInfo.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawReader.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawScanReader.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\W
aters\MassLynxRawScanStatsReader.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\a
bi\vc10\LicenseKey.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\a
bi\vc9\LicenseKey.h
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\x64\Interop.EDAL.SxS.manifest
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\x64\Interop.HSREADWRITELib.SxS.manifest
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\x86\Interop.EDAL.SxS.manifest
Missing revision info in: C:\pwiz-mzdb-master\pwiz_aux\msrc\utility\vendor_api\B
ruker\x86\Interop.HSREADWRITELib.SxS.manifest
ProteoWizard 3.0.7320 (last committed change: 2015-3-18) x64 AMD64
tar.list hdf5-1.8.7.tar.bz2
tar.extract hdf5-1.8.7.tar.bz2 (already extracted)
tar.list boost_1_56_0.tar.bz2
tar.extract boost_1_56_0.tar.bz2 (already extracted)
tar.list zlib-1.2.3.tar.bz2
tar.extract zlib-1.2.3.tar.bz2 (already extracted)
Extracting vendor APIs...
warning: No toolsets are configured.
warning: Configuring default toolset "msvc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html

C:/pwiz-mzdb-master/libraries/boost-build/build\property.jam:526: in property.tr
anslate from module property
C:/pwiz-mzdb-master/libraries/boost-build/build\property-set.jam:432: in propert
y-set.create-from-user-input from module property-set
C:/pwiz-mzdb-master/libraries/boost-build/build\property-set.jam:484: in propert
y-set.refine-from-user-input from module property-set
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:1598: in targets.mai
n-target-requirements from module targets
C:/pwiz-mzdb-master/libraries/boost-build/tools\builtin.jam:534: in lib from mod
ule builtin
pwiz_mzdb\mzdb\writer\Jamfile.jam:4: in modules.load from module Jamfile</C:/pwi
z-mzdb-master/pwiz_mzdb/mzdb/writer>
C:/pwiz-mzdb-master/libraries/boost-build/build\project.jam:298: in load-jamfile
 from module project
C:/pwiz-mzdb-master/libraries/boost-build/build\project.jam:64: in load from mod
ule project
C:/pwiz-mzdb-master/libraries/boost-build/build\project.jam:145: in project.find
 from module project
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:435: in find-really
from module object(project-target)@354
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:457: in class@projec
t-target.find from module object(project-target)@354
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:388: in find-really
from module object(project-target)@354
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:457: in class@projec
t-target.find from module object(project-target)@354
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:841: in resolve-refe
rence from module targets
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:858: in targets.gene
rate-from-reference from module targets
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:1245: in generate-de
pendencies from module object(typed-target)@358
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:1299: in class@basic
-target.generate from module object(typed-target)@358
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:757: in generate-rea
lly from module object(main-target)@369
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:729: in class@main-t
arget.generate from module object(main-target)@369
C:/pwiz-mzdb-master/libraries/boost-build/build\targets.jam:272: in class@projec
t-target.generate from module object(project-target)@354
C:/pwiz-mzdb-master/libraries/boost-build\build-system.jam:707: in load from mod
ule build-system
C:\pwiz-mzdb-master\libraries\boost-build\kernel\modules.jam:289: in import from
 module modules
C:\pwiz-mzdb-master\libraries\boost-build\kernel\bootstrap.jam:139: in boost-bui
ld from module
C:\pwiz-mzdb-master\libraries\boost-build\boost-build.jam:8: in module scope fro
m module

Build finished at 12:05:29.91
Elapsed time: 0:0:11`

**Comment by AlexandreBurel** [comment]
This jamfile should be working just fine without any modification.
You don't have the gsl.lib issue anymore but it stops way too soon now, not sure it's a step forward :p

I know that you said you have followed the instructions, but can you please just confirm that you have done exactly the following ? (setting up MSVC environment for ProteoWizard is tricky and annoying so It may be possible that your problem comes from this)
- Install Visual Studio 2010 Ultimate (I've tried older and newer versions and it did not work, not sure about other 2010 versions)
- execute successfully vcvarsall.bat
- after compiling, check that the real output has been generated (especially raw2mzDB.exe) in " project_root/build-nt-x86\pwiz_mzdb\msvc-10.0\release\address-model-64\asynch-exceptions-on\build-no\link-static\threading-multi" (this is the default output location but you can change it in the main jamfile)

Compiling should take quite a long time (over 20 minutes), but once you make it work you can use the incremental compiling (just add --incremental to the quickbuild command)

**Comment by LaChoz** [comment]
ok so I did install 2010 ultimate
vcvarsall.bat executed successfully

i can't make the jamfile work without modifications (can't find the gsl.lib)

by any chance would it be quickier if someone (eg; you) could send me the compiled files ?
i need the bruker file support of the latest version

Thank you for the help

**Comment by AlexandreBurel** [comment]
That would probably be quicker :)
I'm working on the next release of raw2mzDB but it's not ready yet. In the meantime you can use this previous release: https://filesender.renater.fr/?s=download&token=dd6771bf-21f0-649e-a3c3-f482b7b6e8a5

**Comment by LaChoz** [comment]
perfect ! thank you very much

now I've tried using the `raw2mzdb.exe -i <rawfilename> -o <outputfilename>` command, with my raw files (bruker qtof ".d" raw data folder) and I get "incorrect syntax"

I placed the files in the same folder as raw2mzdb.exe and typed for example :

`raw2mzdb.exe -i <IMPACT0325_GA6_01_335.d> -o <IMPACT0325_GA6_01_335.mzdb>
`
have you ever tried playing with bruker raw files ? what can go wrong ?

**Comment by AlexandreBurel** [comment]
You have to specify the file you want to convert. The minimum options you have to use is :
raw2mzdb.exe -i input_file.raw

You can type raw2mzdb.exe --help to see other options

**Comment by LaChoz** [comment]
Ok it worked with the analysis.baf file that can be found in Bruker's .d raw data folder.

Many thanks, i'm all set !

**Comment by AlexandreBurel** [comment]
You're welcome :)

**Comment by LaChoz** [comment]
last question, can I batch the process from a folder or several files as an input ?

**Comment by AlexandreBurel** [comment]
This is not possible, you will have to write a script convert all your files

**Comment by LaChoz** [comment]
would you, by any chance, have a template of such a script ?

**Comment by AlexandreBurel** [comment]
Yes I do :)
I modified it from an old script of mine and I did not test it but it should work (or need very few modifications ^^)
I had to rename it to ".txt" to upload it, just remove the extension to have a ".bat" file :)
Also, you will have to edit the script to put the path of your converter.

[raw2mzdb-0.9.8d.bat.txt](https://github.com/mzdb/pwiz-mzdb/files/336629/raw2mzdb-0.9.8d.bat.txt)

**Comment by LaChoz** [comment]
works flawlessly !

now I think i'm definitely set !

Cheers.
