### ISSUE TITLE
"Can not create database...Locked, space ?" on wiff files

### ISSUE THREAD

**Issue by iquasere** [mzdb/pwiz-mzdb#67]
Sorry for bothering again, David xD

I have tried to convert my wiff files to mzdb, and have encountered this error.
```
I1118 17:40:57.769676 10112 mzdb_writer.hpp:232] AB Sciex metadata extractor created
I1118 17:40:57.785310 10112 mzdb_writer.cpp:406] updating dataProcessing...
I1118 17:40:57.785310 10112 mzdb_writer.cpp:1051] DDA / DIA test
I1118 17:42:07.225293 10112 mzdb_writer.cpp:1056] DDA Mode detected
I1118 17:42:07.225293 10112 raw2mzDB.cpp:611]

************ Summary of the parameters ************

Treating file: Cursos GTPB\formicicum_proteomics\wiff\CS1_1uL.wiff (DDA ABI WIFF format)
MS 1    Selected Mode: FITTED
MS 2    Selected Mode: CENTROID

Bounding box dimensions:
MS 1    m/z: 5 Da, retention time: 15sec
MS n    m/z: 10000 Da, retention time: 0sec

I1118 17:42:07.225293 10112 mzdb_writer.hpp:352]
I1118 17:42:07.225293 10112 mzdb_writer.hpp:353] SQLITE VERSION: 3.8.9
I1118 17:42:07.225293 10112 mzdb_writer.hpp:354] ProteoWizard release: 3.0.7320 (2015-3-18)
I1118 17:42:07.225293 10112 mzdb_writer.hpp:355] ProteoWizard MSData: 3.0.7303 (2015-3-13)
F1118 17:42:07.272192 10112 mzdb_writer.hpp:360] Can not create database...Locked, space ? Exiting
*** Check failure stack trace: ***
```
I have not been able to find the stack trace as well. Without error traceback, I do not know how to deal with this issue.

Thank you for your attention

**Comment by AlexandreBurel** [comment]
Hi João,

Try to use "/" or "\\" in your path instead of "\". The converter does not understand the "\" as a separator and so it tries to create a file named "GTPB\formicicum_proteomics\wiff\CS1_1uL.wiff.mzDB" which is not allowed by the system.
I'm sure it's just that :)

Alex

**Comment by iquasere** [comment]
Thank you, the problem was in fact in the input, but I didn't quite understand what you said. I had a space in the path to the file, after changing with underscore it was fixed!
