### ISSUE TITLE
Unknown binary data type

### ISSUE THREAD

**Issue by shutinet** [mzdb/pwiz-mzdb#70]
Hi, 
I cannot convert mzML files to mzDB, can you help me figure why ? You can find one of the file tested here if it can help : [https://filesender.renater.fr/?s=download&token=8e2e30a6-2490-4a11-b466-b455eaa7f09f](https://filesender.renater.fr/?s=download&token=8e2e30a6-2490-4a11-b466-b455eaa7f09f)
This is what the tool print on the console : [](https://filesender.renater.fr/?s=download&token=8e2e30a6-2490-4a11-b466-b455eaa7f09f)
```
C:\Users\shutinet\raw2mzDB_0.9.10_build20170802\raw2mzDB.exe -i 200204PLF_QC01_pos.mzML -o QC01.mzDB -c 1
W0524 17:00:18.823838 13504 mzdb_writer.hpp:236] Metadata extraction is not supported for this file format:mzML format
I0524 17:00:18.825130 13504 mzdb_writer.cpp:1051] DDA / DIA test
I0524 17:00:18.837133 13504 mzdb_writer.cpp:1056] DDA Mode detected
I0524 17:00:18.838148 13504 raw2mzDB.cpp:611]

************ Summary of the parameters ************

Treating file: 200204PLF_QC01_pos.mzML (DDA mzML format)
MS 1    Selected Mode: CENTROID
MS 2    Selected Mode: CENTROID

Bounding box dimensions:
MS 1    m/z: 5 Da, retention time: 15sec
MS n    m/z: 10000 Da, retention time: 0sec

I0524 17:00:18.839138 13504 mzdb_writer.hpp:352]
I0524 17:00:18.839138 13504 mzdb_writer.hpp:353] SQLITE VERSION: 3.8.9
I0524 17:00:18.840140 13504 mzdb_writer.hpp:354] ProteoWizard release: 3.0.7320 (2015-3-18)
I0524 17:00:18.841135 13504 mzdb_writer.hpp:355] ProteoWizard MSData: 3.0.7303 (2015-3-13)
I0524 17:00:18.841660 13504 mzdb_writer.cpp:97] Settings SQLite pragmas...
I0524 17:00:18.842495 13504 mzdb_writer.cpp:121] Create database tables...
I0524 17:00:18.845501 13504 mzdb_writer.cpp:695] Pwiz Sample was empty. Filling it...
I0524 17:00:18.846503 13504 mzdb_writer.cpp:743] use default source file
E0524 17:00:18.850106 13504 mzdb_writer.hpp:371] Error occured during metadata insertion.
E0524 17:00:18.850106 13504 mzdb_writer.hpp:372]        ->[IO::HandlerBinaryDataArray] Unknown binary data type.
I0524 17:00:18.851006 13504 mzdb_writer.hpp:390] SpectrumList size: 2762
I0524 17:00:18.852005 13504 mzdb_writer.hpp:412] #detected core(s): 8
I0524 17:00:18.852005 13504 mzdb_writer.hpp:515] Default spectrumList
I0524 17:00:18.852005 13504 mzdb_writer.hpp:523] DDA producer/consumer
```
Thank you very much. I very appreciate any suggestions or help you may have.

**Comment by AlexandreBurel** [comment]
Hello,
There seem to be a problem with the conversion of mzML files, I had the same issue with a QExactive Plus raw file converted to mzML with msconvert : it just stops at the same step as you...
Unfortunately, this converter will probably not be updated anymore because it requires to update and compile all its dependencies which is really difficult and time-consuming. Its replacement is [mzdb4s ](https://github.com/mzdb/mzdb4s) but it does not support mzML (or Waters) files for the moment.

**Comment by shutinet** [comment]
Okay, thank you for your response ! I will look for mzdb4s when it will support mzML or mzXML files :)
